services:
  ingestor:
    # custom_constraints: fixed-host
    labels: ['testing','another']
    image: 54.189.193.228:5000/tester
    ports: 
      ssh: 22
    environment:
      # APP_NAME: Charles Dickens
      # KEYSPACE_NAME: 'flask_keyspace2'
      # TABLE_NAME: 'flask_table2'
    instances: 1
    cpus: 0.1 
    mem: 128
  # ingestor_another:
  #     labels: ['ha']
  #     image: 54.189.193.228:5000/tester
  #     ports: 
  #       ssh: 22
  #     environment:
  #     instances: 1
  #     cpus: 0.1 
  #     mem: 128
