ingestor: {}
presenter:
  '[''halogen'', ''main'', ''money'']':
    cpus: 0.1
    environment: {APP_NAME: D Liu Yo Dawg, KEYSPACE_NAME: flask_keyspace2, TABLE_NAME: flask_table2}
    image: 54.189.193.228:5000/flask
    instances: 2
    labels: [main, halogen, money]
    ports: {api: 5000, ssh: 22}
  '[''halogen'', ''main'']':
    cpus: 0.1
    custom_constraints: fixed-host
    environment: {APP_NAME: D Liu Yo Dawg, KEYSPACE_NAME: flask_keyspace2, TABLE_NAME: flask_table2}
    image: 54.189.193.228:5000/flask
    instances: 2
    labels: [main, halogen]
    ports: {api: 5000, ssh: 22}
  '[''main'']':
    cpus: 0.1
    custom_constraints: fixed-host
    environment: {APP_NAME: Yum Kipper, KEYSPACE_NAME: flask_keyspace2, TABLE_NAME: flask_table2}
    image: 54.189.193.228:5000/flask
    instances: 2
    labels: [main]
    ports: {api: 5000, ssh: 22}
