cassandra:
  '[''dev'']':
    cpus: 0.3
    environment: {MIN_NODES: 2}
    image: 54.189.193.228:5000/cassandra
    instances: 2
    labels: [dev]
    mem: 1024
    ports-hard: {native: 9042, storage: 7000, thrift: 9160}
    volumes: ['/home/ser/ubuntu/volume-test:/opt/testvolume']
haproxy:
  '[''dev'']':
    environment: {PROXY_PORT: api, PROXY_SERVICE: ingestor, WATCHES: ingestor}
    image: 54.189.193.228:5000/haproxy
    labels: [dev]
    ports: {idk: 443, proxy: 80, ssh: 22, suscriber: 5000}
  '[''testing'']':
    environment: {PROXY_LABELS: testing, PROXY_PORT: api, PROXY_SERVICE: ingestor,
      WATCHES: ingestor}
    image: 54.189.193.228:5000/haproxy
    labels: [testing]
    ports: {idk: 443, proxy: 80, ssh: 22, suscriber: 5000}
ingestor:
  '[''dev'']':
    cpus: 0.1
    environment: {APP_NAME: Ingestor, KEYSPACE_NAME: flask_keyspace2, TABLE_NAME: flask_table2}
    image: 54.189.193.228:5000/flask
    instances: 3
    labels: [dev]
    mem: 32
    ports: {api: 5000, ssh: 22}
  '[''testing'']':
    cpus: 0.1
    environment: {APP_NAME: asdf, KEYSPACE_NAME: flask_keyspace2, TABLE_NAME: flask_table2}
    image: 54.189.193.228:5000/flask
    instances: 4
    labels: [testing]
    mem: 32
    ports: {api: 5000, ssh: 22}
presenter:
  '[''dev'']':
    cpus: 0.1
    environment: {APP_NAME: Presenter, KEYSPACE_NAME: flask_keyspace2, TABLE_NAME: flask_table2}
    image: 54.189.193.228:5000/flask
    labels: [dev]
    ports: {api: 5000, ssh: 22}
