cassandra:
  '[''testing'']':
    cpus: 0.3
    environment: {MIN_NODES: 2}
    image: 54.189.193.228:5000/cassandra
    instances: 2
    labels: [testing]
    mem: 1024
    ports-hard: {native: 9042, storage: 7000, thrift: 9160}
    volumes: ['/home/ser/ubuntu/volume-test:/opt/testvolume']
haproxy:
  '[''label_watcher'', ''second'']':
    environment: {PROXY_LABELS: testing, PROXY_PORT: api, PROXY_SERVICE: ingestor,
      WATCHES: ingestor}
    image: 54.189.193.228:5000/haproxy
    labels: [second, label_watcher]
    ports: {idk: 443, proxy: 80, ssh: 22, suscriber: 5000}
  '[''main'']':
    environment: {PROXY_PORT: api, PROXY_SERVICE: ingestor, WATCHES: ingestor}
    image: 54.189.193.228:5000/haproxy
    labels: [main]
    ports: {idk: 443, proxy: 80, ssh: 22, suscriber: 5000}
ingestor:
  '[''dragons'', ''fairydust'', ''hello'', ''ponies'']':
    cpus: 0.1
    environment: {APP_NAME: ChinaTown, KEYSPACE_NAME: flask_keyspace2, TABLE_NAME: flask_table2}
    image: 54.189.193.228:5000/flask
    instances: 3
    labels: [hello, ponies, dragons, fairydust]
    mem: 128
    ports: {api: 5000, ssh: 22}
  '[''testing'']':
    cpus: 0.1
    environment: {APP_NAME: Charles Dickens, KEYSPACE_NAME: flask_keyspace2, TABLE_NAME: flask_table2}
    image: 54.189.193.228:5000/flask
    instances: 3
    labels: [testing]
    mem: 128
    ports: {api: 5000, ssh: 22}
my_name_is_david:
  '[''halogen'', ''hoohoo'', ''main'', ''money'']':
    cpus: 0.05
    custom_constraints: fixed-host
    environment: {APP_NAME: D Liu Yo Dawg Mayn, KEYSPACE_NAME: flask_keyspace2, TABLE_NAME: flask_table2}
    image: 54.189.193.228:5000/flask
    instances: 2
    labels: [main, halogen, money, hoohoo]
    mem: 128
    ports: {api: 5000, ssh: 22}
