haproxy:
  '[''dev'', ''testing'']':
    environment: {PROXY_PORT: api, PROXY_SERVICE: ingestor, WATCHES: ingestor}
    image: 54.189.193.228:5000/haproxy
    labels: [testing, dev]
    ports: {idk: 443, proxy: 80, ssh: 22, suscriber: 5000}
  '[''testing'']':
    environment: {PROXY_PORT: api, PROXY_SERVICE: ingestor, WATCHES: ingestor}
    image: 54.189.193.228:5000/haproxy
    labels: [testing]
    ports: {idk: 443, proxy: 80, ssh: 22, suscriber: 5000}
ingestor:
  '[''testing'']':
    cpus: 0.1
    environment: {APP_NAME: David Is Da Best Dawg in Da Howse, KEYSPACE_NAME: flask_keyspace2,
      TABLE_NAME: flask_table2}
    image: 54.189.193.228:5000/flask
    instances: 3
    labels: [testing]
    mem: 32
    ports: {api: 5000, ssh: 22}
